namespace SimpleLogin
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class FontAwesomeIcons
    {
        /// <summary>
        /// fa-envelope unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid
        /// <para/>
        /// See https://fontawesome.com/icons/envelope
        /// </summary>
        public const string Envelope = "\uf0e0";

        /// <summary>
        /// fa-lock unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/lock
        /// </summary>
        public const string Lock = "\uf023";
    }
}
